spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_test_01?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: com/dylan/mybatis/mapper/xml/**/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql