spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # 选择Redis数据库
    database: 1
    password:
    # 读取超时，单位毫秒, 命令发送到 Redis 服务器并等待响应时间
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）,最多有8个数据库连接
        # 一般把maxActive设置成可能的并发量就行了, 0为没有限制。
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # 连接池中连接用完时,新的请求等待时间,单位毫秒
        max-wait: -1
        # 连接池中的最大空闲连接, 多出的空闲连接会被清除
        max-idle: 8
        # 连接池中的最小空闲连接，少的空闲连接将会被创建
        min-idle: 0
    connect-timeout: